# Site settings
title: "Data Mining In Action"
email: DataMiningInAction@gmail.com
description: "Moscow Institute of Physics and Technology"
baseurl: ""
url: "http:///ml-mipt.github.io"
github_username: vkantor

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge